// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "messages.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace flutter_tts {
using flutter::BasicMessageChannel;
using flutter::CustomEncodableValue;
using flutter::EncodableList;
using flutter::EncodableMap;
using flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
  return FlutterError(
      "channel-error",
      "Unable to establish connection on channel: '" + channel_name + "'.",
      EncodableValue(""));
}

// Voice

Voice::Voice(
  const std::string& name,
  const std::string& locale)
 : name_(name),
    locale_(locale) {}

Voice::Voice(
  const std::string& name,
  const std::string& locale,
  const std::string* gender,
  const std::string* quality,
  const std::string* identifier)
 : name_(name),
    locale_(locale),
    gender_(gender ? std::optional<std::string>(*gender) : std::nullopt),
    quality_(quality ? std::optional<std::string>(*quality) : std::nullopt),
    identifier_(identifier ? std::optional<std::string>(*identifier) : std::nullopt) {}

const std::string& Voice::name() const {
  return name_;
}

void Voice::set_name(std::string_view value_arg) {
  name_ = value_arg;
}


const std::string& Voice::locale() const {
  return locale_;
}

void Voice::set_locale(std::string_view value_arg) {
  locale_ = value_arg;
}


const std::string* Voice::gender() const {
  return gender_ ? &(*gender_) : nullptr;
}

void Voice::set_gender(const std::string_view* value_arg) {
  gender_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void Voice::set_gender(std::string_view value_arg) {
  gender_ = value_arg;
}


const std::string* Voice::quality() const {
  return quality_ ? &(*quality_) : nullptr;
}

void Voice::set_quality(const std::string_view* value_arg) {
  quality_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void Voice::set_quality(std::string_view value_arg) {
  quality_ = value_arg;
}


const std::string* Voice::identifier() const {
  return identifier_ ? &(*identifier_) : nullptr;
}

void Voice::set_identifier(const std::string_view* value_arg) {
  identifier_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void Voice::set_identifier(std::string_view value_arg) {
  identifier_ = value_arg;
}


EncodableList Voice::ToEncodableList() const {
  EncodableList list;
  list.reserve(5);
  list.push_back(EncodableValue(name_));
  list.push_back(EncodableValue(locale_));
  list.push_back(gender_ ? EncodableValue(*gender_) : EncodableValue());
  list.push_back(quality_ ? EncodableValue(*quality_) : EncodableValue());
  list.push_back(identifier_ ? EncodableValue(*identifier_) : EncodableValue());
  return list;
}

Voice Voice::FromEncodableList(const EncodableList& list) {
  Voice decoded(
    std::get<std::string>(list[0]),
    std::get<std::string>(list[1]));
  auto& encodable_gender = list[2];
  if (!encodable_gender.IsNull()) {
    decoded.set_gender(std::get<std::string>(encodable_gender));
  }
  auto& encodable_quality = list[3];
  if (!encodable_quality.IsNull()) {
    decoded.set_quality(std::get<std::string>(encodable_quality));
  }
  auto& encodable_identifier = list[4];
  if (!encodable_identifier.IsNull()) {
    decoded.set_identifier(std::get<std::string>(encodable_identifier));
  }
  return decoded;
}

// TtsResult

TtsResult::TtsResult(bool success)
 : success_(success) {}

TtsResult::TtsResult(
  bool success,
  const std::string* message)
 : success_(success),
    message_(message ? std::optional<std::string>(*message) : std::nullopt) {}

bool TtsResult::success() const {
  return success_;
}

void TtsResult::set_success(bool value_arg) {
  success_ = value_arg;
}


const std::string* TtsResult::message() const {
  return message_ ? &(*message_) : nullptr;
}

void TtsResult::set_message(const std::string_view* value_arg) {
  message_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void TtsResult::set_message(std::string_view value_arg) {
  message_ = value_arg;
}


EncodableList TtsResult::ToEncodableList() const {
  EncodableList list;
  list.reserve(2);
  list.push_back(EncodableValue(success_));
  list.push_back(message_ ? EncodableValue(*message_) : EncodableValue());
  return list;
}

TtsResult TtsResult::FromEncodableList(const EncodableList& list) {
  TtsResult decoded(
    std::get<bool>(list[0]));
  auto& encodable_message = list[1];
  if (!encodable_message.IsNull()) {
    decoded.set_message(std::get<std::string>(encodable_message));
  }
  return decoded;
}

// TtsProgress

TtsProgress::TtsProgress(
  const std::string& text,
  int64_t start,
  int64_t end,
  const std::string& word)
 : text_(text),
    start_(start),
    end_(end),
    word_(word) {}

const std::string& TtsProgress::text() const {
  return text_;
}

void TtsProgress::set_text(std::string_view value_arg) {
  text_ = value_arg;
}


int64_t TtsProgress::start() const {
  return start_;
}

void TtsProgress::set_start(int64_t value_arg) {
  start_ = value_arg;
}


int64_t TtsProgress::end() const {
  return end_;
}

void TtsProgress::set_end(int64_t value_arg) {
  end_ = value_arg;
}


const std::string& TtsProgress::word() const {
  return word_;
}

void TtsProgress::set_word(std::string_view value_arg) {
  word_ = value_arg;
}


EncodableList TtsProgress::ToEncodableList() const {
  EncodableList list;
  list.reserve(4);
  list.push_back(EncodableValue(text_));
  list.push_back(EncodableValue(start_));
  list.push_back(EncodableValue(end_));
  list.push_back(EncodableValue(word_));
  return list;
}

TtsProgress TtsProgress::FromEncodableList(const EncodableList& list) {
  TtsProgress decoded(
    std::get<std::string>(list[0]),
    std::get<int64_t>(list[1]),
    std::get<int64_t>(list[2]),
    std::get<std::string>(list[3]));
  return decoded;
}

// TtsRateValidRange

TtsRateValidRange::TtsRateValidRange(
  double minimum,
  double normal,
  double maximum,
  const TtsPlatform& platform)
 : minimum_(minimum),
    normal_(normal),
    maximum_(maximum),
    platform_(platform) {}

double TtsRateValidRange::minimum() const {
  return minimum_;
}

void TtsRateValidRange::set_minimum(double value_arg) {
  minimum_ = value_arg;
}


double TtsRateValidRange::normal() const {
  return normal_;
}

void TtsRateValidRange::set_normal(double value_arg) {
  normal_ = value_arg;
}


double TtsRateValidRange::maximum() const {
  return maximum_;
}

void TtsRateValidRange::set_maximum(double value_arg) {
  maximum_ = value_arg;
}


const TtsPlatform& TtsRateValidRange::platform() const {
  return platform_;
}

void TtsRateValidRange::set_platform(const TtsPlatform& value_arg) {
  platform_ = value_arg;
}


EncodableList TtsRateValidRange::ToEncodableList() const {
  EncodableList list;
  list.reserve(4);
  list.push_back(EncodableValue(minimum_));
  list.push_back(EncodableValue(normal_));
  list.push_back(EncodableValue(maximum_));
  list.push_back(CustomEncodableValue(platform_));
  return list;
}

TtsRateValidRange TtsRateValidRange::FromEncodableList(const EncodableList& list) {
  TtsRateValidRange decoded(
    std::get<double>(list[0]),
    std::get<double>(list[1]),
    std::get<double>(list[2]),
    std::any_cast<const TtsPlatform&>(std::get<CustomEncodableValue>(list[3])));
  return decoded;
}


PigeonInternalCodecSerializer::PigeonInternalCodecSerializer() {}

EncodableValue PigeonInternalCodecSerializer::ReadValueOfType(
  uint8_t type,
  flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 129: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<FlutterTtsErrorCode>(enum_arg_value));
      }
    case 130: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<IosTextToSpeechAudioCategory>(enum_arg_value));
      }
    case 131: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<IosTextToSpeechAudioMode>(enum_arg_value));
      }
    case 132: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<IosTextToSpeechAudioCategoryOptions>(enum_arg_value));
      }
    case 133: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<TtsPlatform>(enum_arg_value));
      }
    case 134: {
        return CustomEncodableValue(Voice::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 135: {
        return CustomEncodableValue(TtsResult::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 136: {
        return CustomEncodableValue(TtsProgress::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 137: {
        return CustomEncodableValue(TtsRateValidRange::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    default:
      return flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
    }
}

void PigeonInternalCodecSerializer::WriteValue(
  const EncodableValue& value,
  flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(FlutterTtsErrorCode)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<FlutterTtsErrorCode>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(IosTextToSpeechAudioCategory)) {
      stream->WriteByte(130);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<IosTextToSpeechAudioCategory>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(IosTextToSpeechAudioMode)) {
      stream->WriteByte(131);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<IosTextToSpeechAudioMode>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(IosTextToSpeechAudioCategoryOptions)) {
      stream->WriteByte(132);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<IosTextToSpeechAudioCategoryOptions>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(TtsPlatform)) {
      stream->WriteByte(133);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<TtsPlatform>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(Voice)) {
      stream->WriteByte(134);
      WriteValue(EncodableValue(std::any_cast<Voice>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(TtsResult)) {
      stream->WriteByte(135);
      WriteValue(EncodableValue(std::any_cast<TtsResult>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(TtsProgress)) {
      stream->WriteByte(136);
      WriteValue(EncodableValue(std::any_cast<TtsProgress>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(TtsRateValidRange)) {
      stream->WriteByte(137);
      WriteValue(EncodableValue(std::any_cast<TtsRateValidRange>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by TtsHostApi.
const flutter::StandardMessageCodec& TtsHostApi::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `TtsHostApi` to handle messages through the `binary_messenger`.
void TtsHostApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  TtsHostApi* api) {
  TtsHostApi::SetUp(binary_messenger, api, "");
}

void TtsHostApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  TtsHostApi* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_tts.TtsHostApi.speak" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_text_arg = args.at(0);
          if (encodable_text_arg.IsNull()) {
            reply(WrapError("text_arg unexpectedly null."));
            return;
          }
          const auto& text_arg = std::get<std::string>(encodable_text_arg);
          const auto& encodable_force_focus_arg = args.at(1);
          if (encodable_force_focus_arg.IsNull()) {
            reply(WrapError("force_focus_arg unexpectedly null."));
            return;
          }
          const auto& force_focus_arg = std::get<bool>(encodable_force_focus_arg);
          api->Speak(text_arg, force_focus_arg, [reply](ErrorOr<TtsResult>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_tts.TtsHostApi.pause" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->Pause([reply](ErrorOr<TtsResult>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_tts.TtsHostApi.stop" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->Stop([reply](ErrorOr<TtsResult>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_tts.TtsHostApi.setSpeechRate" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_rate_arg = args.at(0);
          if (encodable_rate_arg.IsNull()) {
            reply(WrapError("rate_arg unexpectedly null."));
            return;
          }
          const auto& rate_arg = std::get<double>(encodable_rate_arg);
          api->SetSpeechRate(rate_arg, [reply](ErrorOr<TtsResult>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_tts.TtsHostApi.setVolume" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_volume_arg = args.at(0);
          if (encodable_volume_arg.IsNull()) {
            reply(WrapError("volume_arg unexpectedly null."));
            return;
          }
          const auto& volume_arg = std::get<double>(encodable_volume_arg);
          api->SetVolume(volume_arg, [reply](ErrorOr<TtsResult>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_tts.TtsHostApi.setPitch" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_pitch_arg = args.at(0);
          if (encodable_pitch_arg.IsNull()) {
            reply(WrapError("pitch_arg unexpectedly null."));
            return;
          }
          const auto& pitch_arg = std::get<double>(encodable_pitch_arg);
          api->SetPitch(pitch_arg, [reply](ErrorOr<TtsResult>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_tts.TtsHostApi.setVoice" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_voice_arg = args.at(0);
          if (encodable_voice_arg.IsNull()) {
            reply(WrapError("voice_arg unexpectedly null."));
            return;
          }
          const auto& voice_arg = std::any_cast<const Voice&>(std::get<CustomEncodableValue>(encodable_voice_arg));
          api->SetVoice(voice_arg, [reply](ErrorOr<TtsResult>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_tts.TtsHostApi.clearVoice" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->ClearVoice([reply](ErrorOr<TtsResult>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_tts.TtsHostApi.awaitSpeakCompletion" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_await_completion_arg = args.at(0);
          if (encodable_await_completion_arg.IsNull()) {
            reply(WrapError("await_completion_arg unexpectedly null."));
            return;
          }
          const auto& await_completion_arg = std::get<bool>(encodable_await_completion_arg);
          api->AwaitSpeakCompletion(await_completion_arg, [reply](ErrorOr<TtsResult>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_tts.TtsHostApi.getLanguages" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->GetLanguages([reply](ErrorOr<EncodableList>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_tts.TtsHostApi.getVoices" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->GetVoices([reply](ErrorOr<EncodableList>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue TtsHostApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue TtsHostApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

/// The codec used by IosTtsHostApi.
const flutter::StandardMessageCodec& IosTtsHostApi::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `IosTtsHostApi` to handle messages through the `binary_messenger`.
void IosTtsHostApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  IosTtsHostApi* api) {
  IosTtsHostApi::SetUp(binary_messenger, api, "");
}

void IosTtsHostApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  IosTtsHostApi* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_tts.IosTtsHostApi.awaitSynthCompletion" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_await_completion_arg = args.at(0);
          if (encodable_await_completion_arg.IsNull()) {
            reply(WrapError("await_completion_arg unexpectedly null."));
            return;
          }
          const auto& await_completion_arg = std::get<bool>(encodable_await_completion_arg);
          api->AwaitSynthCompletion(await_completion_arg, [reply](ErrorOr<TtsResult>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_tts.IosTtsHostApi.synthesizeToFile" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_text_arg = args.at(0);
          if (encodable_text_arg.IsNull()) {
            reply(WrapError("text_arg unexpectedly null."));
            return;
          }
          const auto& text_arg = std::get<std::string>(encodable_text_arg);
          const auto& encodable_file_name_arg = args.at(1);
          if (encodable_file_name_arg.IsNull()) {
            reply(WrapError("file_name_arg unexpectedly null."));
            return;
          }
          const auto& file_name_arg = std::get<std::string>(encodable_file_name_arg);
          const auto& encodable_is_full_path_arg = args.at(2);
          if (encodable_is_full_path_arg.IsNull()) {
            reply(WrapError("is_full_path_arg unexpectedly null."));
            return;
          }
          const auto& is_full_path_arg = std::get<bool>(encodable_is_full_path_arg);
          api->SynthesizeToFile(text_arg, file_name_arg, is_full_path_arg, [reply](ErrorOr<TtsResult>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_tts.IosTtsHostApi.setSharedInstance" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_shared_session_arg = args.at(0);
          if (encodable_shared_session_arg.IsNull()) {
            reply(WrapError("shared_session_arg unexpectedly null."));
            return;
          }
          const auto& shared_session_arg = std::get<bool>(encodable_shared_session_arg);
          api->SetSharedInstance(shared_session_arg, [reply](ErrorOr<TtsResult>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_tts.IosTtsHostApi.autoStopSharedSession" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_auto_stop_arg = args.at(0);
          if (encodable_auto_stop_arg.IsNull()) {
            reply(WrapError("auto_stop_arg unexpectedly null."));
            return;
          }
          const auto& auto_stop_arg = std::get<bool>(encodable_auto_stop_arg);
          api->AutoStopSharedSession(auto_stop_arg, [reply](ErrorOr<TtsResult>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_tts.IosTtsHostApi.setIosAudioCategory" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_category_arg = args.at(0);
          if (encodable_category_arg.IsNull()) {
            reply(WrapError("category_arg unexpectedly null."));
            return;
          }
          const auto& category_arg = std::any_cast<const IosTextToSpeechAudioCategory&>(std::get<CustomEncodableValue>(encodable_category_arg));
          const auto& encodable_options_arg = args.at(1);
          if (encodable_options_arg.IsNull()) {
            reply(WrapError("options_arg unexpectedly null."));
            return;
          }
          const auto& options_arg = std::get<EncodableList>(encodable_options_arg);
          const auto& encodable_mode_arg = args.at(2);
          if (encodable_mode_arg.IsNull()) {
            reply(WrapError("mode_arg unexpectedly null."));
            return;
          }
          const auto& mode_arg = std::any_cast<const IosTextToSpeechAudioMode&>(std::get<CustomEncodableValue>(encodable_mode_arg));
          api->SetIosAudioCategory(category_arg, options_arg, mode_arg, [reply](ErrorOr<TtsResult>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_tts.IosTtsHostApi.getSpeechRateValidRange" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->GetSpeechRateValidRange([reply](ErrorOr<TtsRateValidRange>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_tts.IosTtsHostApi.isLanguageAvailable" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_language_arg = args.at(0);
          if (encodable_language_arg.IsNull()) {
            reply(WrapError("language_arg unexpectedly null."));
            return;
          }
          const auto& language_arg = std::get<std::string>(encodable_language_arg);
          api->IsLanguageAvailable(language_arg, [reply](ErrorOr<bool>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_tts.IosTtsHostApi.setLanguange" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_language_arg = args.at(0);
          if (encodable_language_arg.IsNull()) {
            reply(WrapError("language_arg unexpectedly null."));
            return;
          }
          const auto& language_arg = std::get<std::string>(encodable_language_arg);
          api->SetLanguange(language_arg, [reply](ErrorOr<TtsResult>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue IosTtsHostApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue IosTtsHostApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

/// The codec used by AndroidTtsHostApi.
const flutter::StandardMessageCodec& AndroidTtsHostApi::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `AndroidTtsHostApi` to handle messages through the `binary_messenger`.
void AndroidTtsHostApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  AndroidTtsHostApi* api) {
  AndroidTtsHostApi::SetUp(binary_messenger, api, "");
}

void AndroidTtsHostApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  AndroidTtsHostApi* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_tts.AndroidTtsHostApi.awaitSynthCompletion" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_await_completion_arg = args.at(0);
          if (encodable_await_completion_arg.IsNull()) {
            reply(WrapError("await_completion_arg unexpectedly null."));
            return;
          }
          const auto& await_completion_arg = std::get<bool>(encodable_await_completion_arg);
          api->AwaitSynthCompletion(await_completion_arg, [reply](ErrorOr<TtsResult>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_tts.AndroidTtsHostApi.getMaxSpeechInputLength" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->GetMaxSpeechInputLength([reply](ErrorOr<std::optional<int64_t>>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            auto output_optional = std::move(output).TakeValue();
            if (output_optional) {
              wrapped.push_back(EncodableValue(std::move(output_optional).value()));
            } else {
              wrapped.push_back(EncodableValue());
            }
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_tts.AndroidTtsHostApi.setEngine" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_engine_arg = args.at(0);
          if (encodable_engine_arg.IsNull()) {
            reply(WrapError("engine_arg unexpectedly null."));
            return;
          }
          const auto& engine_arg = std::get<std::string>(encodable_engine_arg);
          api->SetEngine(engine_arg, [reply](ErrorOr<TtsResult>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_tts.AndroidTtsHostApi.getEngines" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->GetEngines([reply](ErrorOr<EncodableList>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_tts.AndroidTtsHostApi.getDefaultEngine" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->GetDefaultEngine([reply](ErrorOr<std::optional<std::string>>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            auto output_optional = std::move(output).TakeValue();
            if (output_optional) {
              wrapped.push_back(EncodableValue(std::move(output_optional).value()));
            } else {
              wrapped.push_back(EncodableValue());
            }
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_tts.AndroidTtsHostApi.getDefaultVoice" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->GetDefaultVoice([reply](ErrorOr<std::optional<Voice>>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            auto output_optional = std::move(output).TakeValue();
            if (output_optional) {
              wrapped.push_back(CustomEncodableValue(std::move(output_optional).value()));
            } else {
              wrapped.push_back(EncodableValue());
            }
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_tts.AndroidTtsHostApi.synthesizeToFile" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_text_arg = args.at(0);
          if (encodable_text_arg.IsNull()) {
            reply(WrapError("text_arg unexpectedly null."));
            return;
          }
          const auto& text_arg = std::get<std::string>(encodable_text_arg);
          const auto& encodable_file_name_arg = args.at(1);
          if (encodable_file_name_arg.IsNull()) {
            reply(WrapError("file_name_arg unexpectedly null."));
            return;
          }
          const auto& file_name_arg = std::get<std::string>(encodable_file_name_arg);
          const auto& encodable_is_full_path_arg = args.at(2);
          if (encodable_is_full_path_arg.IsNull()) {
            reply(WrapError("is_full_path_arg unexpectedly null."));
            return;
          }
          const auto& is_full_path_arg = std::get<bool>(encodable_is_full_path_arg);
          api->SynthesizeToFile(text_arg, file_name_arg, is_full_path_arg, [reply](ErrorOr<TtsResult>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_tts.AndroidTtsHostApi.isLanguageInstalled" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_language_arg = args.at(0);
          if (encodable_language_arg.IsNull()) {
            reply(WrapError("language_arg unexpectedly null."));
            return;
          }
          const auto& language_arg = std::get<std::string>(encodable_language_arg);
          api->IsLanguageInstalled(language_arg, [reply](ErrorOr<bool>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_tts.AndroidTtsHostApi.isLanguageAvailable" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_language_arg = args.at(0);
          if (encodable_language_arg.IsNull()) {
            reply(WrapError("language_arg unexpectedly null."));
            return;
          }
          const auto& language_arg = std::get<std::string>(encodable_language_arg);
          api->IsLanguageAvailable(language_arg, [reply](ErrorOr<bool>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_tts.AndroidTtsHostApi.areLanguagesInstalled" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_languages_arg = args.at(0);
          if (encodable_languages_arg.IsNull()) {
            reply(WrapError("languages_arg unexpectedly null."));
            return;
          }
          const auto& languages_arg = std::get<EncodableList>(encodable_languages_arg);
          api->AreLanguagesInstalled(languages_arg, [reply](ErrorOr<EncodableMap>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_tts.AndroidTtsHostApi.getSpeechRateValidRange" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->GetSpeechRateValidRange([reply](ErrorOr<TtsRateValidRange>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_tts.AndroidTtsHostApi.setSilence" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_timems_arg = args.at(0);
          if (encodable_timems_arg.IsNull()) {
            reply(WrapError("timems_arg unexpectedly null."));
            return;
          }
          const int64_t timems_arg = encodable_timems_arg.LongValue();
          api->SetSilence(timems_arg, [reply](ErrorOr<TtsResult>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_tts.AndroidTtsHostApi.setQueueMode" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_queue_mode_arg = args.at(0);
          if (encodable_queue_mode_arg.IsNull()) {
            reply(WrapError("queue_mode_arg unexpectedly null."));
            return;
          }
          const int64_t queue_mode_arg = encodable_queue_mode_arg.LongValue();
          api->SetQueueMode(queue_mode_arg, [reply](ErrorOr<TtsResult>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_tts.AndroidTtsHostApi.setAudioAttributesForNavigation" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->SetAudioAttributesForNavigation([reply](ErrorOr<TtsResult>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue AndroidTtsHostApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue AndroidTtsHostApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

/// The codec used by MacosTtsHostApi.
const flutter::StandardMessageCodec& MacosTtsHostApi::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `MacosTtsHostApi` to handle messages through the `binary_messenger`.
void MacosTtsHostApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  MacosTtsHostApi* api) {
  MacosTtsHostApi::SetUp(binary_messenger, api, "");
}

void MacosTtsHostApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  MacosTtsHostApi* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_tts.MacosTtsHostApi.awaitSynthCompletion" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_await_completion_arg = args.at(0);
          if (encodable_await_completion_arg.IsNull()) {
            reply(WrapError("await_completion_arg unexpectedly null."));
            return;
          }
          const auto& await_completion_arg = std::get<bool>(encodable_await_completion_arg);
          api->AwaitSynthCompletion(await_completion_arg, [reply](ErrorOr<TtsResult>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_tts.MacosTtsHostApi.getSpeechRateValidRange" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->GetSpeechRateValidRange([reply](ErrorOr<TtsRateValidRange>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_tts.MacosTtsHostApi.setLanguange" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_language_arg = args.at(0);
          if (encodable_language_arg.IsNull()) {
            reply(WrapError("language_arg unexpectedly null."));
            return;
          }
          const auto& language_arg = std::get<std::string>(encodable_language_arg);
          api->SetLanguange(language_arg, [reply](ErrorOr<TtsResult>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_tts.MacosTtsHostApi.isLanguageAvailable" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_language_arg = args.at(0);
          if (encodable_language_arg.IsNull()) {
            reply(WrapError("language_arg unexpectedly null."));
            return;
          }
          const auto& language_arg = std::get<std::string>(encodable_language_arg);
          api->IsLanguageAvailable(language_arg, [reply](ErrorOr<bool>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue MacosTtsHostApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue MacosTtsHostApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

// Generated class from Pigeon that represents Flutter messages that can be called from C++.
TtsFlutterApi::TtsFlutterApi(flutter::BinaryMessenger* binary_messenger)
 : binary_messenger_(binary_messenger),
    message_channel_suffix_("") {}

TtsFlutterApi::TtsFlutterApi(
  flutter::BinaryMessenger* binary_messenger,
  const std::string& message_channel_suffix)
 : binary_messenger_(binary_messenger),
    message_channel_suffix_(message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "") {}

const flutter::StandardMessageCodec& TtsFlutterApi::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

void TtsFlutterApi::OnSpeakStartCb(
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.flutter_tts.TtsFlutterApi.onSpeakStartCb" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue();
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

void TtsFlutterApi::OnSpeakCompleteCb(
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.flutter_tts.TtsFlutterApi.onSpeakCompleteCb" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue();
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

void TtsFlutterApi::OnSpeakPauseCb(
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.flutter_tts.TtsFlutterApi.onSpeakPauseCb" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue();
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

void TtsFlutterApi::OnSpeakResumeCb(
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.flutter_tts.TtsFlutterApi.onSpeakResumeCb" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue();
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

void TtsFlutterApi::OnSpeakCancelCb(
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.flutter_tts.TtsFlutterApi.onSpeakCancelCb" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue();
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

void TtsFlutterApi::OnSpeakProgressCb(
  const TtsProgress& progress_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.flutter_tts.TtsFlutterApi.onSpeakProgressCb" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    CustomEncodableValue(progress_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

void TtsFlutterApi::OnSpeakErrorCb(
  const std::string& error_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.flutter_tts.TtsFlutterApi.onSpeakErrorCb" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    EncodableValue(error_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

void TtsFlutterApi::OnSynthStartCb(
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.flutter_tts.TtsFlutterApi.onSynthStartCb" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue();
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

void TtsFlutterApi::OnSynthCompleteCb(
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.flutter_tts.TtsFlutterApi.onSynthCompleteCb" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue();
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

void TtsFlutterApi::OnSynthErrorCb(
  const std::string& error_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.flutter_tts.TtsFlutterApi.onSynthErrorCb" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    EncodableValue(error_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

}  // namespace flutter_tts
