analyzer:
  strong-mode:
    implicit-casts: false
  errors:
    unused_import: error
    unused_local_variable: error
    dead_code: error
linter:
  rules:
     - avoid_empty_else
     - comment_references
     - control_flow_in_finally
     - empty_statements
     - hash_and_equals
     - only_throw_errors
     - test_types_in_equals
     - throw_in_finally
     - unrelated_type_equality_checks
     - valid_regexps
     - avoid_init_to_null
     - avoid_return_types_on_setters
     - await_only_futures
     - camel_case_types
     - directives_ordering
     - empty_catches
     - empty_constructor_bodies
     - library_names
     - library_prefixes
     - non_constant_identifier_names
     - omit_local_variable_types
     - prefer_final_fields
     - prefer_is_not_empty
     - prefer_typing_uninitialized_variables
     - slash_for_doc_comments
     - type_init_formals